version: '3.8'

services:
  pharmacy-app-prod:
    build:
      context: .
      target: production
    container_name: pharmacy_app_production
    ports:
      - "8080:80"
    volumes:
      - ./data:/app/data  # Mount local data directory for SQLite file persistence
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - pharmacy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  pharmacy-network:
    driver: bridge 